#!/usr/bin/env python3
"""Generate docs/releases/changelog.md from GitHub Releases.

Run from the repository root (also invoked by `just docs` and the docs CI
workflow). Uses the public GitHub API; set GITHUB_TOKEN or GH_TOKEN for a
higher rate limit when available.
"""

from __future__ import annotations

import json
import os
import re
import sys
import urllib.error
import urllib.request
from pathlib import Path

REPO = "dennisme/grex"
API = f"https://api.github.com/repos/{REPO}/releases?per_page=100"
OUT = Path("docs/releases/changelog.md")

HEADER = """\
# Changelog

<!-- Generated by scripts/generate-releases-changelog.py — do not edit by hand. -->

Release notes from [GitHub Releases](https://github.com/{repo}/releases),
produced by GoReleaser (GitHub-native notes). This page is regenerated when
the docs site is built.

For install coordinates (binary, container, Helm), see [Releases](index.md).
Maintainer process: [Developer: Releasing](../developer/releasing.md).
"""


def fetch_releases() -> list[dict]:
    req = urllib.request.Request(
        API,
        headers={
            "Accept": "application/vnd.github+json",
            "User-Agent": "grex-docs-changelog",
            "X-GitHub-Api-Version": "2022-11-28",
        },
    )
    token = os.environ.get("GITHUB_TOKEN") or os.environ.get("GH_TOKEN")
    if token:
        req.add_header("Authorization", f"Bearer {token}")
    with urllib.request.urlopen(req, timeout=45) as resp:
        data = json.load(resp)
    if not isinstance(data, list):
        raise RuntimeError(f"unexpected API response type: {type(data)}")
    return data


def markdownify_github_notes(body: str) -> str:
    """Turn GitHub-native release notes into MkDocs-friendly Markdown links.

    GitHub's UI auto-links bare URLs and @mentions; Python-Markdown does not
    unless magiclink is enabled. Convert explicitly so PR/user links always
    work on the Pages site.
    """
    # Drop GoReleaser install footer (Docker/Helm blocks). Docs already list
    # coordinates under "Get this release", and the footer fences fail md lint.
    parts = re.split(r"\n---\s*\n", body, maxsplit=1)
    if len(parts) == 2 and "**Docker:**" in parts[1]:
        body = parts[0].rstrip()

    # "* title by @user in https://github.com/org/repo/pull/123"
    body = re.sub(
        r"by @([A-Za-z0-9-]+) in (https://github\.com/[^/\s]+/[^/\s]+/pull/(\d+))",
        r"by [@\1](https://github.com/\1) in [#\3](\2)",
        body,
    )
    # "@user made their first contribution in https://github.com/.../pull/N"
    body = re.sub(
        r"@([A-Za-z0-9-]+) made their first contribution in "
        r"(https://github\.com/[^/\s]+/[^/\s]+/pull/(\d+))",
        r"[@\1](https://github.com/\1) made their first contribution in [#\3](\2)",
        body,
    )
    # "**Full Changelog**: https://..."
    body = re.sub(
        r"(\*\*Full Changelog\*\*:\s*)(https://\S+)",
        r"\1[\2](\2)",
        body,
    )
    # Any remaining bare https://github.com/... URLs not already in markdown.
    body = re.sub(
        r"(?<!\]\()(?<!\[)(https://github\.com/[^\s)<>]+)",
        r"[\1](\1)",
        body,
    )
    # GitHub uses "* " lists; this repo's markdownlint prefers "- ".
    body = re.sub(r"(?m)^\* ", "- ", body)
    # Blank line before ## headings (except at start).
    body = re.sub(r"(?m)([^\n])\n(## )", r"\1\n\n\2", body)
    # Blank line after ## headings when a list follows immediately.
    body = re.sub(r"(?m)^(## .+)\n(- )", r"\1\n\n\2", body)
    # Collapse runs of blank lines.
    body = re.sub(r"\n{3,}", "\n\n", body)
    return body.strip()


def render(releases: list[dict]) -> str:
    lines = [HEADER.format(repo=REPO)]
    published = [r for r in releases if not r.get("draft")]
    if not published:
        lines += [
            "No published GitHub Releases yet. After the first tagged release",
            "(`just release-tag`), notes and downloadable assets appear here",
            "on the next docs build.",
            "",
            f"Track progress on the [releases page](https://github.com/{REPO}/releases).",
            "",
        ]
        return "\n".join(lines)

    for r in published:
        tag = r.get("tag_name") or "unknown"
        name = (r.get("name") or tag).strip() or tag
        url = r.get("html_url") or f"https://github.com/{REPO}/releases/tag/{tag}"
        published_at = (r.get("published_at") or "")[:10]
        body = markdownify_github_notes((r.get("body") or "").strip())
        prerelease = bool(r.get("prerelease"))

        heading = f"## [{name}]({url})"
        lines.append(heading)
        lines.append("")
        meta = [f"**Tag:** `{tag}`"]
        if published_at:
            meta.append(f"**Published:** {published_at}")
        if prerelease:
            meta.append("**Pre-release**")
        lines.append(" · ".join(meta))
        lines.append("")

        # Quick artifact coordinates for this version (SemVer without leading v).
        ver = tag[1:] if tag.startswith("v") else tag
        lines += [
            "### Get this release",
            "",
            f"- [GitHub Release]({url}) (binaries, checksums, chart `.tgz`)",
            f"- Container: `ghcr.io/dennisme/grex:{ver}`",
            f"- Helm (Pages): `helm upgrade --install grex grex/grex --version {ver}`",
            f"- Helm (OCI): `helm upgrade --install grex oci://ghcr.io/dennisme/charts/grex --version {ver}`",
            "",
        ]

        assets = r.get("assets") or []
        if assets:
            lines.append("### Assets")
            lines.append("")
            for a in assets:
                aname = a.get("name") or "asset"
                aurl = a.get("browser_download_url") or url
                lines.append(f"- [{aname}]({aurl})")
            lines.append("")

        if body:
            lines.append(body)
            lines.append("")
        else:
            lines.append("_No release notes body was published for this tag._")
            lines.append("")

        lines.append("---")
        lines.append("")

    # Drop trailing horizontal rule / blank-line noise
    while lines and lines[-1] in ("", "---"):
        lines.pop()
    text = "\n".join(lines).rstrip() + "\n"
    return re.sub(r"\n{3,}", "\n\n", text)


def main() -> int:
    try:
        releases = fetch_releases()
    except (urllib.error.URLError, urllib.error.HTTPError, TimeoutError, RuntimeError) as exc:
        if OUT.is_file():
            print(f"warning: could not refresh changelog ({exc}); keeping {OUT}", file=sys.stderr)
            return 0
        print(f"warning: could not fetch releases ({exc}); writing empty changelog", file=sys.stderr)
        releases = []

    OUT.parent.mkdir(parents=True, exist_ok=True)
    text = render(releases)
    OUT.write_text(text, encoding="utf-8")
    n = len([r for r in releases if not r.get("draft")])
    print(f"wrote {OUT} ({n} release(s))")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
